### ISSUE TITLE
Oprava domácího úkolu: Životopis

### ISSUE THREAD

**Issue by LenkaVer** [karolinavaitt/Zivotopis#1]
Ahoj Karolíno, 
moc pěkná stránka, kód je přehledný. Přikládám moje postřehy:
V úvodu bych obalila img a h1 do tagu header buď společně s menu nebo bych menu obalila do tagu nav.
Názvy tříd by měly být napsané malými písmeny, nejčastěji se používá kebab-case (tedy oddělování slov pomlčkou), případně nějaké konvence jako je BEM (budeme se učit dále v kurzu).

**Comment by karolinavaitt** [comment]
Ahoj Lenko, snad je to správně opravené.
